#!/bin/bash
#SBATCH -N 1
#SBATCH -t 72:00:00
#SBATCH --exclude=mscluster68,mscluster48,mscluster82,mscluster61,mscluster72
#SBATCH --ntasks=1
#SBATCH --partition=biggpu

echo ------------------------------------------------------
echo -n 'Job is running on node ' $SLURM_JOB_NODELIST
echo ------------------------------------------------------
echo SLURM: sbatch is running on $SLURM_SUBMIT_HOST
echo SLURM: job ID is $SLURM_JOB_ID
echo SLURM: submit directory is $SLURM_SUBMIT_DIR
echo SLURM: number of nodes allocated is $SLURM_JOB_NUM_NODES
echo SLURM: number of cores is $SLURM_NTASKS
echo SLURM: job name is $SLURM_JOB_NAME
echo ------------------------------------------------------

/bin/hostname
nvidia-smi
source ~/.bashrc
conda activate NeRF
export CUDA_VISIBLE_DEVICES=0
echo "Launching the script ${SLURM_JOB_NAME}"
# ./scripts/viton/viton.sh $SLURM_JOB_NAME {experiment_number}  {run_number} {experiment_from}  {run_number_from}
# ./scripts/viton/viton.sh $SLURM_JOB_NAME 1 6 1 6




export EXPERIMENT_NUMBER=13
export EXPERIMENT_FROM_NUMBER=11
export RUN_NUMBER=99
export RUN_FROM_NUMBER=0
export DATASET_NAME=Original
export TASK=GEN
export DEBUG=1
export DATAMODE=train
export VITON_NAME=HR_VITON

echo "Start Debug: $DEBUG"
echo "Experiment Number: $EXPERIMENT_NUMBER"
echo "Experiment From Number: $EXPERIMENT_FROM_NUMBER"
echo "Run Number: $RUN_NUMBER"
echo "Run From Number: $RUN_FROM_NUMBER"
echo "Dataset Name: $DATASET_NAME"


# tocg_experiment_from_number 11 - Original
# tocg_experiment_from_number 12 - Rail

# gen_experiment_from_number 13 - Original
# gen_experiment_from_number 14 - Rail


./scripts/viton/viton.sh --job_name $VITON_NAME --experiment_number $EXPERIMENT_NUMBER --run_number $RUN_NUMBER \
  --experiment_from_number $EXPERIMENT_FROM_NUMBER --run_from_number $RUN_FROM_NUMBER \
  --tocg_experiment_from_number 0 --tocg_run_from_number 0 \
  --tocg_discriminator_experiment_from_number 0 --tocg_discriminator_run_from_number 0 \
  --tocg_load_from_model Original --tocg_discriminator_load_from_model Original \
  --gen_experiment_from_number 0 --gen_run_from_number 0 \
  --gen_discriminator_experiment_from_number 0 --gen_discriminator_run_from_number 0 \
  --gen_load_from_model Original --gen_discriminator_load_from_model Original \
  --VITON_Type Parser_Based --VITON_Name $VITON_NAME --VITON_Model $TASK --load_last_step False \
  --gpu_ids 1 --device 1 --res high_res --dataset_name $DATASET_NAME --run_wandb False \
  --niter 1 --niter_decay 1 --display_count 1 --print_step 1 --save_period 1 \
  --viton_batch_size 4 --datamode $DATAMODE --debug $DEBUG